server {
    listen RENDER_PORT default_server;
    listen [::]:RENDER_PORT default_server;

    root /var/www/html;
    index index.html;

    # 1. 炫酷前端界面
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. 简化后的代理路径
    location /v2 {
        if ($http_upgrade != "websocket") {
            return 404;
        }
        proxy_redirect off;
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
